### ISSUE TITLE
puppeteer Chromium 启动失败 获取Mac地址失败

### ISSUE THREAD

**Issue by cky008** [yoimiya-kokomi/Miao-Yunzai#130]
无法使用，弱弱问下怎么解决呢..使用的是甲骨文云的4+24 ARM架构机器

环境：
```
Red Hat Enterprise Linux release 8.8 (Ootpa)
Linux version 5.15.0-7.86.6.1.el8uek.aarch64
```

具体报错： 
```
[MiaoYz][10:33:10.005][MARK] puppeteer Chromium 启动中...
获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

[MiaoYz][10:33:10.033][ERRO] {}
Error: Failed to launch the browser process!
/root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome: /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome: cannot execute binary file


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (file:///root/Miao-Yunzai/node_modules/.pnpm/@puppeteer+browsers@1.3.0/node_modules/@puppeteer/browsers/lib/esm/launch.js:253:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:533:10)
    at Socket.onend (node:internal/readline/interface:259:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined
[MiaoYz][10:33:10.035][ERRO] puppeteer Chromium 启动失败
```

**Comment by ITManCHINA** [comment]
和楼主遇到了同样的问题

环境：
`CentOS Stream release 9 aarch64`

报错：
`[MiaoYz][12:40:37.571][MARK] puppeteer Chromium 启动中...
获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

[MiaoYz][12:40:37.620][ERRO] {}
Error: Failed to launch the browser process! spawn /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome ENOENT


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (file:///root/Miao-Yunzai/node_modules/.pnpm/@puppeteer+browsers@1.3.0/node_modules/@puppeteer/browsers/lib/esm/launch.js:253:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined
[MiaoYz][12:40:37.627][ERRO] puppeteer Chromium 启动失败`

**Comment by ITManCHINA** [comment]
和楼主遇到了同样的问题

环境：
`CentOS Stream release 9 aarch64`

报错：
```
[MiaoYz][12:40:37.571][MARK] puppeteer Chromium 启动中...
获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

[MiaoYz][12:40:37.620][ERRO] {}
Error: Failed to launch the browser process! spawn /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome ENOENT


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (file:///root/Miao-Yunzai/node_modules/.pnpm/@puppeteer+browsers@1.3.0/node_modules/@puppeteer/browsers/lib/esm/launch.js:253:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined
[MiaoYz][12:40:37.627][ERRO] puppeteer Chromium 启动失败
```

**Comment by ITManCHINA** [comment]
> 和楼主遇到了同样的问题
> 
> 环境： `CentOS Stream release 9 aarch64`
> 
> 报错：
> 
> ```
> [MiaoYz][12:40:37.571][MARK] puppeteer Chromium 启动中...
> 获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')
> 
>   Puppeteer old Headless deprecation warning:
>     In the near feature `headless: true` will default to the new Headless mode
>     for Chrome instead of the old Headless implementation. For more
>     information, please see https://developer.chrome.com/articles/new-headless/.
>     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
>     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
> 
> [MiaoYz][12:40:37.620][ERRO] {}
> Error: Failed to launch the browser process! spawn /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome ENOENT
> 
> 
> TROUBLESHOOTING: https://pptr.dev/troubleshooting
> 
>     at ChildProcess.onClose (file:///root/Miao-Yunzai/node_modules/.pnpm/@puppeteer+browsers@1.3.0/node_modules/@puppeteer/browsers/lib/esm/launch.js:253:24)
>     at ChildProcess.emit (node:events:513:28)
>     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
>     at onErrorNT (node:internal/child_process:476:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined
> [MiaoYz][12:40:37.627][ERRO] puppeteer Chromium 启动失败
> ```

问题已解决，在尝试使用pnpm install puppeteer@13.7.0 -w命令将puppeteer降级为13.7.0版本即可启动Chrome
此时的报错信息为：
```
[MiaoYz][14:28:55.613][MARK] puppeteer Chromium 启动中...  获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')
chromium ws://127.0.0.1:37579/devtools/browser/1bcd7f4a-1228-4492-b020-4d1c0045ebde
[MiaoYz][14:28:58.162][MARK] puppeteer Chromium 启动成功
```

**Comment by cky008** [comment]
可行 十分感谢👍
> > 和楼主遇到了同样的问题
> 
> > 
> 
> > 环境： `CentOS Stream release 9 aarch64`
> 
> > 
> 
> > 报错：
> 
> > 
> 
> > ```
> 
> > [MiaoYz][12:40:37.571][MARK] puppeteer Chromium 启动中...
> 
> > 获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')
> 
> > 
> 
> >   Puppeteer old Headless deprecation warning:
> 
> >     In the near feature `headless: true` will default to the new Headless mode
> 
> >     for Chrome instead of the old Headless implementation. For more
> 
> >     information, please see https://developer.chrome.com/articles/new-headless/.
> 
> >     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
> 
> >     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
> 
> > 
> 
> > [MiaoYz][12:40:37.620][ERRO] {}
> 
> > Error: Failed to launch the browser process! spawn /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome ENOENT
> 
> > 
> 
> > 
> 
> > TROUBLESHOOTING: https://pptr.dev/troubleshooting
> 
> > 
> 
> >     at ChildProcess.onClose (file:///root/Miao-Yunzai/node_modules/.pnpm/@puppeteer+browsers@1.3.0/node_modules/@puppeteer/browsers/lib/esm/launch.js:253:24)
> 
> >     at ChildProcess.emit (node:events:513:28)
> 
> >     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
> 
> >     at onErrorNT (node:internal/child_process:476:16)
> 
> >     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined
> 
> > [MiaoYz][12:40:37.627][ERRO] puppeteer Chromium 启动失败
> 
> > ```
> 
> 
> 
> 问题已解决，在尝试使用`pnpm install puppeteer@13.7.0 -w`命令将puppeteer降级为13.7.0版本即可启动Chrome
> 
> 此时的报错信息为：
> 
> ```
> 
> [MiaoYz][14:28:55.613][MARK] puppeteer Chromium 启动中...
> 
> 获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')
> 
> chromium ws://127.0.0.1:37579/devtools/browser/1bcd7f4a-1228-4492-b020-4d1c0045ebde
> 
> [MiaoYz][14:28:58.162][MARK] puppeteer Chromium 启动成功
> 
> ```

**Comment by ITManCHINA** [comment]
> > 和楼主遇到了同样的问题
> > 环境： `CentOS Stream release 9 aarch64`
> > 报错：
> > ```
> > [MiaoYz][12:40:37.571][MARK] puppeteer Chromium 启动中...
> > 获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')
> > 
> >   Puppeteer old Headless deprecation warning:
> >     In the near feature `headless: true` will default to the new Headless mode
> >     for Chrome instead of the old Headless implementation. For more
> >     information, please see https://developer.chrome.com/articles/new-headless/.
> >     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
> >     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
> > 
> > [MiaoYz][12:40:37.620][ERRO] {}
> > Error: Failed to launch the browser process! spawn /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome ENOENT
> > 
> > 
> > TROUBLESHOOTING: https://pptr.dev/troubleshooting
> > 
> >     at ChildProcess.onClose (file:///root/Miao-Yunzai/node_modules/.pnpm/@puppeteer+browsers@1.3.0/node_modules/@puppeteer/browsers/lib/esm/launch.js:253:24)
> >     at ChildProcess.emit (node:events:513:28)
> >     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
> >     at onErrorNT (node:internal/child_process:476:16)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined
> > [MiaoYz][12:40:37.627][ERRO] puppeteer Chromium 启动失败
> > ```
> 
> 问题已解决，在尝试使用`pnpm install puppeteer@13.7.0 -w`命令将puppeteer降级为13.7.0版本即可启动Chrome 此时的报错信息为：
> 
> ```
> [MiaoYz][14:28:55.613][MARK] puppeteer Chromium 启动中...
> 获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')
> chromium ws://127.0.0.1:37579/devtools/browser/1bcd7f4a-1228-4492-b020-4d1c0045ebde
> [MiaoYz][14:28:58.162][MARK] puppeteer Chromium 启动成功
> ```

补充说明，降级puppeteer之后可能会导致`更新面板`功能无法正常使用

错误说明：`MiniGG-API`
```
[MiaoYz][14:29:59.878][MARK] 【面板】110327056 ：请求结束，请求用时268ms，面板服务：MiniGG-Api...
面板请求错误 SyntaxError: Unexpected token M in JSON at position 0 
    at JSON.parse (<anonymous>)
    at Proxy.requestProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/ProfileReq.js:103:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.refreshProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/player/Profile.js:77:7)
    at async Proxy.refreshProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/Player.js:243:12)
    at async cls.refresh (file:///root/Miao-Yunzai/plugins/miao-plugin/apps/profile/ProfileList.js:21:5)
    at async cls.<computed> [as profileRefresh] (file:///root/Miao-Yunzai/plugins/miao-plugin/components/App.js:94:16)
    at async PluginsLoader.deal (file:///root/Miao-Yunzai/lib/plugins/loader.js:254:54)
```
`Enka.network`
```
[MiaoYz][14:42:49.446][INFO] succeed to send: [Group(748394004)] 开始获取uid:110327056的数据，可能会需要一定时间~
[MiaoYz][14:42:49.751][MARK] 【面板】110327056 ：请求结束，请求用时2601ms，面板服务：enka.network...
面板请求错误 SyntaxError: Unexpected token M in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.requestProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/ProfileReq.js:103:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.refreshProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/player/Profile.js:77:7)
    at async Proxy.refreshProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/Player.js:243:12)
    at async cls.refresh (file:///root/Miao-Yunzai/plugins/miao-plugin/apps/profile/ProfileList.js:21:5)
    at async cls.<computed> [as profileRefresh] (file:///root/Miao-Yunzai/plugins/miao-plugin/components/App.js:94:16)
    at async PluginsLoader.deal (file:///root/Miao-Yunzai/lib/plugins/loader.js:254:54)
```

**Comment by cky008** [comment]
这个是原神版本更新导致的 等一段时间就好了 enka.network现在也查不了的 得等api那边搞好

> > > 和楼主遇到了同样的问题
> 
> > > 环境： `CentOS Stream release 9 aarch64`
> 
> > > 报错：
> 
> > > ```
> 
> > > [MiaoYz][12:40:37.571][MARK] puppeteer Chromium 启动中...
> 
> > > 获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')
> 
> > > 
> 
> > >   Puppeteer old Headless deprecation warning:
> 
> > >     In the near feature `headless: true` will default to the new Headless mode
> 
> > >     for Chrome instead of the old Headless implementation. For more
> 
> > >     information, please see https://developer.chrome.com/articles/new-headless/.
> 
> > >     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
> 
> > >     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
> 
> > > 
> 
> > > [MiaoYz][12:40:37.620][ERRO] {}
> 
> > > Error: Failed to launch the browser process! spawn /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome ENOENT
> 
> > > 
> 
> > > 
> 
> > > TROUBLESHOOTING: https://pptr.dev/troubleshooting
> 
> > > 
> 
> > >     at ChildProcess.onClose (file:///root/Miao-Yunzai/node_modules/.pnpm/@puppeteer+browsers@1.3.0/node_modules/@puppeteer/browsers/lib/esm/launch.js:253:24)
> 
> > >     at ChildProcess.emit (node:events:513:28)
> 
> > >     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
> 
> > >     at onErrorNT (node:internal/child_process:476:16)
> 
> > >     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined
> 
> > > [MiaoYz][12:40:37.627][ERRO] puppeteer Chromium 启动失败
> 
> > > ```
> 
> > 
> 
> > 问题已解决，在尝试使用`pnpm install puppeteer@13.7.0 -w`命令将puppeteer降级为13.7.0版本即可启动Chrome 此时的报错信息为：
> 
> > 
> 
> > ```
> 
> > [MiaoYz][14:28:55.613][MARK] puppeteer Chromium 启动中...
> 
> > 获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')
> 
> > chromium ws://127.0.0.1:37579/devtools/browser/1bcd7f4a-1228-4492-b020-4d1c0045ebde
> 
> > [MiaoYz][14:28:58.162][MARK] puppeteer Chromium 启动成功
> 
> > ```
> 
> 
> 
> 补充说明，降级puppeteer之后可能会导致`更新面板`功能无法正常使用
> 
> 
> 
> 错误说明：`MiniGG-API`
> 
> ```
> 
> [MiaoYz][14:29:59.878][MARK] 【面板】110327056 ：请求结束，请求用时268ms，面板服务：MiniGG-Api...
> 
> 面板请求错误 SyntaxError: Unexpected token M in JSON at position 0 
> 
>     at JSON.parse (<anonymous>)
> 
>     at Proxy.requestProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/ProfileReq.js:103:21)
> 
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>     at async Object.refreshProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/player/Profile.js:77:7)
> 
>     at async Proxy.refreshProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/Player.js:243:12)
> 
>     at async cls.refresh (file:///root/Miao-Yunzai/plugins/miao-plugin/apps/profile/ProfileList.js:21:5)
> 
>     at async cls.<computed> [as profileRefresh] (file:///root/Miao-Yunzai/plugins/miao-plugin/components/App.js:94:16)
> 
>     at async PluginsLoader.deal (file:///root/Miao-Yunzai/lib/plugins/loader.js:254:54)
> 
> ```
> 
> `Enka.network`
> 
> ```
> 
> [MiaoYz][14:42:49.751][MARK] 【面板】110327056 ：请求结束，请求用时2601ms，面板服务：enka.network...
> 
> 面板请求错误 SyntaxError: Unexpected token M in JSON at position 0
> 
>     at JSON.parse (<anonymous>)
> 
>     at Proxy.requestProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/ProfileReq.js:103:21)
> 
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>     at async Object.refreshProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/player/Profile.js:77:7)
> 
>     at async Proxy.refreshProfile (file:///root/Miao-Yunzai/plugins/miao-plugin/models/Player.js:243:12)
> 
>     at async cls.refresh (file:///root/Miao-Yunzai/plugins/miao-plugin/apps/profile/ProfileList.js:21:5)
> 
>     at async cls.<computed> [as profileRefresh] (file:///root/Miao-Yunzai/plugins/miao-plugin/components/App.js:94:16)
> 
>     at async PluginsLoader.deal (file:///root/Miao-Yunzai/lib/plugins/loader.js:254:54)
> 
> ```

**Comment by ITManCHINA** [comment]
明白了

**Comment by ITManCHINA** [comment]
> 这个是原神版本更新导致的 等一段时间就好了 enka.network现在也查不了的 得等api那边搞好
> 

明白了，感谢解答

**Comment by XJLZ** [comment]
应该是网卡的名称和代码（renderers/puppeteer/lib/puppeteer.js  157行）写的不一致。代码里是eth0 但自身服务器的网卡名称可能不叫eth0，也有可能是ens32或者其他名称，可以使用命令 ifconfig 查看
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/28652248/c91a567d-1761-4505-bfc1-bf2f3cbd1c1a)
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/28652248/b33f5669-33d1-44e6-b5e6-849bfe2cb4d7)

**Comment by MainasuK** [comment]
```
[MiaoYz][13:09:24.727][MARK] puppeteer Chromium 启动中...                                                                       
获取Mac地址失败 TypeError: Cannot read properties of undefined (reading 'filter')                                               
[MiaoYz][13:09:24.757][ERRO] {}                                                                                                 
Error: Failed to launch the browser process!                                                                                    
/home/ubuntu/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome: 4: Syntax error: Unterminated quoted string     
                                                                                                                                
                                                                                                                                
TROUBLESHOOTING: https://pptr.dev/troubleshooting                                                                               
                                                                                                                                
    at Interface.onClose (file:///home/ubuntu/Developer/Miao-Yunzai/node_modules/.pnpm/@puppeteer+browsers@1.4.1/node_modules/@p
uppeteer/browsers/lib/esm/launch.js:250:24)                                                                                     
    at Interface.emit (node:events:524:35)                                                                                      
    at Interface.close (node:internal/readline/interface:534:10)                                                                
    at Socket.onend (node:internal/readline/interface:260:10)                                                                   
    at Socket.emit (node:events:524:35)                                                                                         
    at endReadableNT (node:internal/streams/readable:1359:12)                                                                   
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined                                    
[MiaoYz][13:09:24.760][ERRO] puppeteer Chromium 启动失败                                                                        
[MiaoYz][13:09:24.760][MARK] [喵喵:喵喵帮助][help] #帮助 处理完成 43ms                    
```

系统 `Ubuntu 22.04.2 LTS aarch64`

用上面的降级命令之后就没问题了。之前一直是好的，应该是最近更新之后才出问题
