### ISSUE TITLE
喵版云崽刷新群排行仍然读取 data/MysCookie 导致报错

### ISSUE THREAD

**Issue by Tsuk1ko** [yoimiya-kokomi/Miao-Yunzai#147]
```
0|Miao-Yunzai  | [MiaoYz][11:35:30.110][ERRO] [喵喵:角色面板][refreshRank]
0|Miao-Yunzai  | [MiaoYz][11:35:30.111][ERRO] Error: ENOENT: no such file or directory, scandir './data/MysCookie/'
0|Miao-Yunzai  |     at Object.readdirSync (node:fs:1438:3)
0|Miao-Yunzai  |     at GsCfg.getBingCk (file:///opt/Miao-Yunzai/plugins/genshin/model/gsCfg.js:101:20)
0|Miao-Yunzai  |     at Object.getNoteQQUids (file:///opt/Miao-Yunzai/plugins/miao-plugin/components/Common.js:21:47)
0|Miao-Yunzai  |     at Object.getGroupUids (file:///opt/Miao-Yunzai/plugins/miao-plugin/components/Common.js:56:33)
0|Miao-Yunzai  |     at cls.refreshRank (file:///opt/Miao-Yunzai/plugins/miao-plugin/apps/profile/ProfileRank.js:126:32)
0|Miao-Yunzai  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Miao-Yunzai  |     at async cls.<computed> [as refreshRank] (file:///opt/Miao-Yunzai/plugins/miao-plugin/components/App.js:94:16)
0|Miao-Yunzai  |     at async PluginsLoader.deal (file:///opt/Miao-Yunzai/lib/plugins/loader.js:254:54)
```

**Comment by Tsuk1ko** [comment]
> 读取不到还会把你该目录直接删掉，即使你后续创建了MysCookie这个文件夹，丢了ck进去，也会被清除，但是不会清除文件夹

大致看了下代码应该是喵版云崽改了储存 ck 的方式，现在全用 sqlite 存了，喵版云崽会自动读取原版云崽 ck 来迁移，完事会删掉文件夹，这个是正常的

问题是某些函数读取 ck 仍然会去这里读，大概是作者忘了改了

**Comment by yoimiya-kokomi** [comment]
更新最新版Miao-Yunzai以及miao-plugin，应该已经适配

**Comment by Tsuk1ko** [comment]
正常了
