### ISSUE TITLE
更新后所有命令失效

### ISSUE THREAD

**Issue by carey892** [yoimiya-kokomi/Miao-Yunzai#152]
阿里云服务器linux，控制台输出命令为

> TypeError: Data.forEach is not a function
    at MysUser.forEach (file:///usr/local/projects/yunzai-bot/Miao-Yunzai/plugins/genshin/model/mys/MysUser.js:71:16)
    at async MysInfo.initUserCk (file:///usr/local/projects/yunzai-bot/Miao-Yunzai/plugins/genshin/model/mys/mysInfo.js:237:5)
    at async MysInfo.initCache (file:///usr/local/projects/yunzai-bot/Miao-Yunzai/plugins/genshin/model/mys/mysInfo.js:265:5)
    at async MysInfo.getNoteUser (file:///usr/local/projects/yunzai-bot/Miao-Yunzai/plugins/genshin/model/mys/mysInfo.js:74:5)
    at async Runtime.init (file:///usr/local/projects/yunzai-bot/Miao-Yunzai/lib/plugins/runtime.js:71:14)
    at async PluginsLoader.deal (file:///usr/local/projects/yunzai-bot/Miao-Yunzai/lib/plugins/loader.js:180:5)

具体操作为：以前都是直接发送命令`#更新`，这次更新后程序莫名没了，顺手`pnpm install`更新了依赖，然后启动程序后所有命令都提示该错误，无法执行。
尝试过`git reset --hard`重置到更新前版本，更新依赖，仍然是该错误。

**Comment by tanyiok1234** [comment]
先倒退回commit 1233964e78c736e7528763d002a189fc26a78dd4吧。。。我也遇到这个问题了，倒退回这个commit就能用了，估计是哪有bug (

**Comment by carey892** [comment]
> 先倒退回commit 1233964e78c736e7528763d002a189fc26a78dd4吧。。。我也遇到这个问题了，倒退回这个commit就能用了，估计是哪有bug (

记得更新miao-plugin
