### ISSUE TITLE
获取角色面板报错

### ISSUE THREAD

**Issue by OliveRuan** [yoimiya-kokomi/Miao-Yunzai#157]
[MiaoYz][10:34:03.885][ERRO] [喵喵:角色面板][YzavatarList]
[MiaoYz][10:34:03.886][ERRO] TypeError: Cannot read properties of undefined (reading 'getAvatarTalent')
    at Proxy.setTalent (file:///C:/Miao-Yunzai/plugins/miao-plugin/models/AvatarData.js:188:27)
    at Proxy.setAvatar (file:///C:/Miao-Yunzai/plugins/miao-plugin/models/AvatarData.js:109:23)
    at Proxy.setAvatar (file:///C:/Miao-Yunzai/plugins/miao-plugin/models/Player.js:165:12)
    at file:///C:/Miao-Yunzai/plugins/miao-plugin/models/Player.js:158:12
    at C:\Miao-Yunzai\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (C:\Miao-Yunzai\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js:3032:24)
    at C:\Miao-Yunzai\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js:4936:18
    at Function.forEach (C:\Miao-Yunzai\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js:9410:14)
    at Proxy.setAvatars (file:///C:/Miao-Yunzai/plugins/miao-plugin/models/Player.js:157:12)
    at Proxy.reload (file:///C:/Miao-Yunzai/plugins/miao-plugin/models/Player.js:89:10)

**Comment by yoimiya-kokomi** [comment]
看报错是角色不存在，先更新下miao-plugin试试
