### ISSUE TITLE
部分指令仅返回说明图片/报错

### ISSUE THREAD

**Issue by Imufan233** [yoimiya-kokomi/Miao-Yunzai#166]
![Screenshot_2023-06-06-02-04-30-363_com tencent mobileqq](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/87289682/fb5a105c-c397-440d-8f60-2581287ca2f7)
![Screenshot_2023-06-06-02-12-16-989_com server auditor ssh client](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/87289682/37faa1ca-3f6b-4260-915e-d2d1a9675c1b)

1|Miao-Yun | [MiaoYz][01:44:12.659][ERRO] [喵 喵 :深 渊 统 计 ][abyssTeam]
1|Miao-Yun | [MiaoYz][01:44:12.659][ERRO] TypeError: Cannot read properties of undefined (reading 'getAvatarTalent')
1|Miao-Yun |     at Proxy.setTalent (file:///root/Miao-Yunzai/plugins/miao-plugin/models/AvatarData.js:162:27)
1|Miao-Yun |     at Proxy.setAvatar (file:///root/Miao-Yunzai/plugins/miao-plugin/models/AvatarData.js:106:23)
1|Miao-Yun |     at Proxy.setAvatar (file:///root/Miao-Yunzai/plugins/miao-plugin/models/Player.js:150:12)
1|Miao-Yun |     at file:///root/Miao-Yunzai/plugins/miao-plugin/models/Player.js:143:12
1|Miao-Yun |     at /root/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:4967:15
1|Miao-Yun |     at baseForOwn (/root/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:3032:24)
1|Miao-Yun |     at /root/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:4936:18
1|Miao-Yun |     at Function.forEach (/root/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:9410:14)
1|Miao-Yun |     at Proxy.setAvatars (file:///root/Miao-Yunzai/plugins/miao-plugin/models/Player.js:142:12)
1|Miao-Yun |     at Proxy.reload (file:///root/Miao-Yunzai/plugins/miao-plugin/models/Player.js:78:10)

**Comment by Imufan233** [comment]
更新喵喵插件后解决
