### ISSUE TITLE
无法输入滑动验证码

### ISSUE THREAD

**Issue by mikezom** [yoimiya-kokomi/Miao-Yunzai#184]
输入ticket，回车之后无任何响应。
Node.js v18.16.0

> [MiaoYz][15:57:20.107][MARK] Miao-Yunzai 启动中...
> [MiaoYz][15:57:20.115][MARK] 正在连接 Redis...
> [MiaoYz][15:57:20.115][MARK] redis://127.0.0.1:6379/0
> [MiaoYz][15:57:20.128][MARK] Redis 连接成功
> [MiaoYz][15:57:20.172][MARK] ----------
> [MiaoYz][15:57:20.176][MARK] Package Version: icqq@0.3.15 (Released on 2023/5/20)
> [MiaoYz][15:57:20.176][MARK] View Changelogs：https://github.com/icqqjs/icqq/releases
> [MiaoYz][15:57:20.176][MARK] ----------
> SyntaxError: Unexpected token '??='
>     at Loader.moduleStrategy (internal/modules/esm/translators.js:149:18)
> [MiaoYz][15:57:20.536][MARK] 监听事件错误：login.js
> [MiaoYz][15:57:20.537][ERRO] TypeError: rendererFn is not a function
>     at registerRendererBackends (file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
>     at async file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:32:1
> [MiaoYz][15:57:20.578][MARK] 监听事件错误：message.js
> [MiaoYz][15:57:20.579][ERRO] TypeError: rendererFn is not a function
>     at registerRendererBackends (file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
>     at async file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:32:1
> [MiaoYz][15:57:20.665][MARK] 监听事件错误：notice.js
> [MiaoYz][15:57:20.665][ERRO] TypeError: rendererFn is not a function
>     at registerRendererBackends (file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
>     at async file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:32:1
> [MiaoYz][15:57:20.686][MARK] 监听事件错误：offline.js
> [MiaoYz][15:57:20.686][ERRO] TypeError: rendererFn is not a function
>     at registerRendererBackends (file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
>     at async file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:32:1
> [MiaoYz][15:57:20.695][MARK] 监听事件错误：online.js
> [MiaoYz][15:57:20.695][ERRO] TypeError: rendererFn is not a function
>     at registerRendererBackends (file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
>     at async file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:32:1
> [MiaoYz][15:57:20.699][MARK] 监听事件错误：request.js
> [MiaoYz][15:57:20.699][ERRO] TypeError: rendererFn is not a function
>     at registerRendererBackends (file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
>     at async file:///home/ubuntu/qbot/Miao-Yunzai/lib/renderer/Renderer.js:32:1
> [MiaoYz][15:57:20.700][INFO] [2905506344]使用协议：Android_8.8.88
> [MiaoYz][15:57:20.939][MARK] 120.241.130.216:8080 connected
> [MiaoYz][15:57:21.067][MARK] 收到滑动验证码，请访问以下地址完成滑动，并从网络响应中取出ticket输入：

**Comment by wuweidmw** [comment]
我也是

**Comment by WorldlineChanger** [comment]
有解决方法吗？

**Comment by WorldlineChanger** [comment]
> 有解决方法吗？

因 CentOS 7 中默认 gcc 版本较低，导致报错 /lib64/libstdc++.so.6: version `CXXABI_1.3.8‘ not found，下载 6.0.26 库文件后重新软链接即可

**Comment by tignioj** [comment]
# 报错：

    
    [MiaoYz][22:56:45.078][MARK] 监听事件错误：online.js
    [MiaoYz][22:56:45.079][ERRO] Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /root/Miao-Yunzai/node_modules/.pnpm/sqlite3@5.1.6/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
        at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
        at Module.load (node:internal/modules/cjs/loader:1076:32)
        at Function.Module._load (node:internal/modules/cjs/loader:911:12)
        at Module.require (node:internal/modules/cjs/loader:1100:19)
        at require (node:internal/modules/cjs/helpers:119:18)
        at Object.<anonymous> (/root/Miao-Yunzai/node_modules/.pnpm/sqlite3@5.1.6/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
        at Module._compile (node:internal/modules/cjs/loader:1198:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
        at Module.load (node:internal/modules/cjs/loader:1076:32)
        at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
      code: 'ERR_DLOPEN_FAILED'
    }
    [MiaoYz][22:56:45.121][MARK] 监听事件错误：request.js
    [MiaoYz][22:56:45.121][ERRO] Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /root/Miao-Yunzai/node_modules/.pnpm/sqlite3@5.1.6/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
        at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
        at Module.load (node:internal/modules/cjs/loader:1076:32)
        at Function.Module._load (node:internal/modules/cjs/loader:911:12)
        at Module.require (node:internal/modules/cjs/loader:1100:19)
        at require (node:internal/modules/cjs/helpers:119:18)
        at Object.<anonymous> (/root/Miao-Yunzai/node_modules/.pnpm/sqlite3@5.1.6/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
        at Module._compile (node:internal/modules/cjs/loader:1198:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
        at Module.load (node:internal/modules/cjs/loader:1076:32)
        at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
      code: 'ERR_DLOPEN_FAILED'


参考： https://github.com/TryGhost/node-sqlite3/issues/1582#issuecomment-1198949710
# 步骤
1. 下载gcc10-libstdc++，来源：https://mirror.ghettoforge.org/distributions/gf/el/7/gf/x86_64/
2. 安装 `rpm -i gcc10-libstdc++-10.2.1-7.gf.el7.x86_64.rpm`, 此时 /opt/会多出一个gcc10目录
3. 设置环境变量并运行miao-yunzai `LD_LIBRARY_PATH=$PATH:/opt/gcc-10.2.1/usr/lib64/ node app`
