### ISSUE TITLE
更新本体或插件后发送更新日志 icqq 会报错 empty message

### ISSUE THREAD

**Issue by Tsuk1ko** [yoimiya-kokomi/Miao-Yunzai#212]
使用的是 f34240511b42fdbcb8a479f01e7cab697f70992f 用 pnpm 更新过依赖了

```
0|Miao-Yun | [MiaoYz][12:33:33.053][MARK] [更新][updateAll] 开始更新：Miao-Yunzai
0|Miao-Yun | [MiaoYz][12:33:35.337][MARK] [更新][updateAll] 最后更新时间：2023-07-26 05:23:14
0|Miao-Yun | [MiaoYz][12:33:36.845][MARK] [更新][updateAll] 开始更新：Guoba-Plugin
0|Miao-Yun | [MiaoYz][12:33:39.591][MARK] [更新][updateAll] 最后更新时间：2023-07-10 01:06:00
0|Miao-Yun | [MiaoYz][12:33:41.099][MARK] [更新][updateAll] 开始更新：miao-plugin
0|Miao-Yun | [MiaoYz][12:33:44.936][ERRO] [更新][updateAll]
0|Miao-Yun | [MiaoYz][12:33:44.937][ERRO] Error: empty message
0|Miao-Yun |     at new Converter (/opt/Miao-Yunzai/node_modules/.pnpm/icqq@0.4.12/node_modules/icqq/lib/message/converter.js:53:19)
0|Miao-Yun |     at Friend.makeForwardMsg (/opt/Miao-Yunzai/node_modules/.pnpm/icqq@0.4.12/node_modules/icqq/lib/internal/contactable.js:521:27)
0|Miao-Yun |     at Object.makeForwardMsg (file:///opt/Miao-Yunzai/lib/common/common.js:95:33)
0|Miao-Yun |     at update.getLog (file:///opt/Miao-Yunzai/plugins/other/update.js:260:24)
0|Miao-Yun |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Miao-Yun |     at async update.runUpdate (file:///opt/Miao-Yunzai/plugins/other/update.js:137:17)
0|Miao-Yun |     at async updateAll (file:///opt/Miao-Yunzai/plugins/other/update.js:215:7)
0|Miao-Yun |     at async PluginsLoader.deal (file:///opt/Miao-Yunzai/lib/plugins/loader.js:269:54)
```

```
0|Miao-Yunzai  | [MiaoYz][12:34:17.155][MARK] [更新][updateAll] 开始更新：Miao-Yunzai
0|Miao-Yunzai  | [MiaoYz][12:34:17.915][MARK] [更新][updateAll] 最后更新时间：2023-07-26 05:23:14
0|Miao-Yunzai  | [MiaoYz][12:34:19.422][MARK] [更新][updateAll] 开始更新：Guoba-Plugin
0|Miao-Yunzai  | [MiaoYz][12:34:20.162][MARK] [更新][updateAll] 最后更新时间：2023-07-10 01:06:00
0|Miao-Yunzai  | [MiaoYz][12:34:21.669][MARK] [更新][updateAll] 开始更新：miao-plugin
0|Miao-Yunzai  | [MiaoYz][12:34:25.568][MARK] [更新][updateAll] 最后更新时间：2023-07-25 21:10:05
0|Miao-Yunzai  | [MiaoYz][12:34:27.075][MARK] [更新][updateAll] 开始更新：xiaoyao-cvs-plugin
0|Miao-Yunzai  | [MiaoYz][12:34:36.588][ERRO] [更新][updateAll]
0|Miao-Yunzai  | [MiaoYz][12:34:36.589][ERRO] Error: empty message
0|Miao-Yunzai  |     at new Converter (/opt/Miao-Yunzai/node_modules/.pnpm/icqq@0.4.12/node_modules/icqq/lib/message/converter.js:53:19)
0|Miao-Yunzai  |     at Friend.makeForwardMsg (/opt/Miao-Yunzai/node_modules/.pnpm/icqq@0.4.12/node_modules/icqq/lib/internal/contactable.js:521:27)
0|Miao-Yunzai  |     at Object.makeForwardMsg (file:///opt/Miao-Yunzai/lib/common/common.js:95:33)
0|Miao-Yunzai  |     at update.getLog (file:///opt/Miao-Yunzai/plugins/other/update.js:260:24)
0|Miao-Yunzai  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Miao-Yunzai  |     at async update.runUpdate (file:///opt/Miao-Yunzai/plugins/other/update.js:137:17)
0|Miao-Yunzai  |     at async updateAll (file:///opt/Miao-Yunzai/plugins/other/update.js:215:7)
0|Miao-Yunzai  |     at async PluginsLoader.deal (file:///opt/Miao-Yunzai/lib/plugins/loader.js:269:54)
```

**Comment by Tsuk1ko** [comment]
新版正常了
