### ISSUE TITLE
公告推送报错

### ISSUE THREAD

**Issue by muguodiao** [yoimiya-kokomi/Miao-Yunzai#281]
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/105115300/6fe76db2-8c7a-4f01-97b3-09173b63fc05)

**Comment by 8852690** [comment]
。。。你把lib/common/common.js的第81行`let info = await e.bot.getGroupMemberInfo(e.group_id, id)`改成`let info = await (e.bot ?? Bot).getGroupMemberInfo(e.group_id, id)`就好，因为米游社新闻推送的e是伪造的，缺少了一部分属性

**Comment by devil233-ui** [comment]
> 。。。你把lib/common/common.js的第81行`let info = await e.bot.getGroupMemberInfo(e.group_id, id)`改成`let info = await (e.bot ?? Bot).getGroupMemberInfo(e.group_id, id)`就好，因为米游社新闻推送的e是伪造的，缺少了一部分属性

请问b站的怎么改
> [12:09:11.372][ERRO] 群[]推送失败：{"code":-60,"message":"client not online (cmd: ImgStore.GroupPicUp)"}
[12:16:40.763][ERRO] 定时任务报错：检测b站推送定时任务
[12:16:40.764][ERRO] FetchError: request to https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?host_mid=318432901 failed, reason: write ECONNABORTED
    at ClientRequest.<anonymous> (file:///C:/Users/Administrator/Desktop/nt-yuunzai/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNABORTED',
  code: 'ECONNABORTED',
  erroredSysCall: 'write'
}

**Comment by 8852690** [comment]
> > 。。。你把lib/common/common.js的第81行`let info = await e.bot.getGroupMemberInfo(e.group_id, id)`改成`let info = await (e.bot ?? Bot).getGroupMemberInfo(e.group_id, id)`就好，因为米游社新闻推送的e是伪造的，缺少了一部分属性
> 
> 请问b站的怎么改
> 
> > [12:09:11.372][ERRO] 群[]推送失败：{"code":-60,"message":"client not online (cmd: ImgStore.GroupPicUp)"}
> > [12:16:40.763][ERRO] 定时任务报错：检测b站推送定时任务
> > [12:16:40.764][ERRO] FetchError: request to https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?host_mid=318432901 failed, reason: write ECONNABORTED
> > at ClientRequest. (file:///C:/Users/Administrator/Desktop/nt-yuunzai/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:108:11)
> > at ClientRequest.emit (node:events:514:28)
> > at TLSSocket.socketErrorListener (node:_http_client:495:9)
> > at TLSSocket.emit (node:events:514:28)
> > at emitErrorNT (node:internal/streams/destroy:151:8)
> > at emitErrorCloseNT (node:internal/streams/destroy:116:3)
> > at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
> > type: 'system',
> > errno: 'ECONNABORTED',
> > code: 'ECONNABORTED',
> > erroredSysCall: 'write'
> > }

这个看起来似乎是闲心那边打不开api，我没用过闲心，不太清楚。这个是在请求数据的时候出错，而不是发送消息的时候异常，跟上述 MYS推送失败 没关系。
