### ISSUE TITLE
[bug]在微信上匹配失败

### ISSUE THREAD

**Issue by slideslide** [yoimiya-kokomi/Miao-Yunzai#342]
# 在微信上匹配失败
## 过程
发送了抽卡记录的json后发生报错
导入失败
## 报错
```
[TRSSYz][16:38:51.137][INFO] [wxid_xmux47s5uubc22] 好友消息：[wxid_xxxxxxxxxxxxxxx] [文件]
[TRSSYz][16:38:51.141][ERRO] TypeError: Cannot read properties of undefined (reading 'includes')
    at gcLog.accept (file:///J:/bots/genshin/yunzaiV3/plugins/genshin/apps/gcLog.js:67:16)
    at PluginsLoader.deal (file:///J:/bots/genshin/yunzaiV3/lib/plugins/loader.js:249:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by 8852690** [comment]
...那不应该，是去trss提吗？
