### ISSUE TITLE
puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by Polarforest** [yoimiya-kokomi/Miao-Yunzai#366]
在使用#绑定uid时出现错误
```
[MiaoYz][18:07:55.241][INFO] <Bot:Zeya(1595*****4)> <好友:Whiskey(2027*****4)> -> #绑定19***8342
[MiaoYz][18:07:55.355][MARK] [用户绑定][bingUid][私聊][Whiskey(2027*****4)] #绑定19***8342                    [MiaoYz][18:07:55.362][INFO] puppeteer Chromium 启动中...
                                                         Puppeteer old Headless deprecation warning:
    In the near future `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more                                               information, please see https://developer.chrome.com/articles/new-headless/.                                  Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
[MiaoYz][18:07:55.365][ERRO] {}
[MiaoYz][18:07:55.365][ERRO] Error: Could not find Chrome (ver. 121.0.6167.85). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///home/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:259:27)
    at ChromeLauncher.executablePath (file:///home/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:204:25)                                           at ChromeLauncher.computeLaunchArguments (file:///home/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:97:37)
    at async ChromeLauncher.launch (file:///home/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:44:28)                                             at async Puppeteer.browserInit (file:///home/Miao-Yunzai/renderers/puppeteer/lib/puppeteer.js:89:22)          at async Puppeteer.screenshot [as render] (file:///home/Miao-Yunzai/renderers/puppeteer/lib/puppeteer.js:172:10)                                                     at async renderer.screenshot (file:///home/Miao-Yunzai/lib/puppeteer/puppeteer.js:10:15)                      at async Runtime.render (file:///home/Miao-Yunzai/lib/plugins/runtime.js:234:18)                              at async User.showUid (file:///home/Miao-Yunzai/plugins/genshin/model/user.js:277:26)                         at async User.bingUid (file:///home/Miao-Yunzai/plugins/genshin/model/user.js:205:12) undefined           [MiaoYz][18:07:55.366][ERRO] puppeteer Chromium 启动失 败
```
设备信息
```
设备型号:Xiaomi 23116PN5BC
Android版本: Android 14
架构: aarch64 (64-bit)
系统：ubuntu23.10
```

**Comment by DreamUniverse843** [comment]
> 更换系统后已解决。

您好，我同样遇到了这个问题，请问您更换到了哪个系统后正常工作？
