### ISSUE TITLE
Puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by DreamUniverse843** [yoimiya-kokomi/Miao-Yunzai#373]
日志：
```
[MiaoYz][00:19:06.804][INFO] puppeteer Chromium 启动中...

  Puppeteer old Headless deprecation warning:
    In the near future `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

[MiaoYz][00:19:06.812][ERRO] {}
[MiaoYz][00:19:06.812][ERRO] Error: Could not find Chrome (ver. 121.0.6167.85). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///root/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:259:27)
    at ChromeLauncher.executablePath (file:///root/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:204:25)
    at ChromeLauncher.computeLaunchArguments (file:///root/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:97:37)
    at async ChromeLauncher.launch (file:///root/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:44:28)
    at async Puppeteer.browserInit (file:///root/Miao-Yunzai/renderers/puppeteer/lib/puppeteer.js:89:22)
    at async Puppeteer.screenshot [as render] (file:///root/Miao-Yunzai/renderers/puppeteer/lib/puppeteer.js:172:10)
    at async renderer.screenshot (file:///root/Miao-Yunzai/lib/puppeteer/puppeteer.js:10:15)
    at async Runtime.render (file:///root/Miao-Yunzai/lib/plugins/runtime.js:234:18)
    at async gacha (file:///root/Miao-Yunzai/plugins/genshin/apps/gacha.js:36:5)
    at async PluginsLoader.deal (file:///root/Miao-Yunzai/lib/plugins/loader.js:292:52) undefined
[MiaoYz][00:19:06.815][ERRO] puppeteer Chromium 启动失败
[MiaoYz][00:19:06.815][INFO] [十连][gacha] 抽卡 处理完成 85ms
```
尝试过手动执行安装 Chrome，依然不能识别。
```
[root@localhost Miao-Yunzai]# npx puppeteer browsers install chrome@121.0.6167.85
[Chromium] undefined
Downloading chrome r121.0.6167.85 - 149.6 MB [====================] 100% 0.0s 
chrome@121.0.6167.85 /root/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome
```

运行环境：
```
Linux localhost 6.2.1-PRoot-Distro #1 SMP PREEMPT Mon Jan 29 10:52:12 CET 2024 aarch64 GNU/Linux
Node.js:v20.10.0
npm:v10.2.3
体系结构:aarch64
设备型号:Xiaomi MI 9
Android版本: Android 14
系统：Fedora 39(经由 TermUX proot-distro 命令安装)
```

**Comment by DreamUniverse843** [comment]
换用 Debian 容器，使用 Debian 源安装 chromium(apt install chromium)后解决。
Debian 源有 chromium 的 ARM64 版本。
可能是 puppeteer 默认下载的非 ARM64 架构而是其他架构所导致。
