### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dnyo666** [yoimiya-kokomi/Miao-Yunzai#405]
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/73740313/d95d1910-f7d7-4ddc-960b-021ca71a9396)
[MiaoYz][23:38:54.726][INFO] recv from: [Group: 枫迹の交流群①(303104111), Member: 浅巷墨黎(2315823357)] #状态
[MiaoYz][23:38:54.728][INFO] recv from: [Group: 枫迹の交流群①(303104111), Member: 浅巷墨黎(2315823357)] #状态
[MiaoYz][23:38:54.729][INFO] recv from: [Group: 枫迹の交流群①(303104111), Member: 浅巷墨黎(2315823357)] #状态
[MiaoYz][23:38:54.747][INFO] recv from: [Group: 枫迹の交流群①(303104111), Member: 浅巷墨黎(2315823357)] #状态
[MiaoYz][23:38:54.760][INFO] [咸鱼_统计][adduser][枫迹の交流群①(浅巷墨黎)] #状态
[MiaoYz][23:38:54.912][INFO] [椰奶状态][state][枫迹の交流群①(浅巷墨黎)] #状态
[MiaoYz][23:38:54.919][ERRO] TypeError: Cannot read properties of undefined (reading 'group_id')
    at PluginsLoader.checkDisable (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/lib/plugins/loader.js:709:39)
    at file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:37:23
    at Array.forEach (<anonymous>)
    at PluginsLoader.deal (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:33:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/cmd.js:85:13)
[MiaoYz][23:38:54.921][ERRO] TypeError: Cannot read properties of undefined (reading 'group_id')
    at PluginsLoader.checkDisable (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/lib/plugins/loader.js:709:39)
    at file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:37:23
    at Array.forEach (<anonymous>)
    at PluginsLoader.deal (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:33:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/cmd.js:85:13)
[MiaoYz][23:38:54.926][ERRO] TypeError: Cannot read properties of undefined (reading 'group_id')
    at PluginsLoader.checkDisable (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/lib/plugins/loader.js:709:39)
    at file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:37:23
    at Array.forEach (<anonymous>)
    at PluginsLoader.deal (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:33:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/cmd.js:85:13)
[MiaoYz][23:38:56.981][MARK] [图片生成][yenai-plugin/state/state][2次] 609.26KB 1777ms
[MiaoYz][23:38:58.528][INFO] recv from: [Group: 枫迹の交流群①(303104111), Member: 枫音酱(1932289274)] {image:C0AA009A9A38DBF08F0272521E9D43F2}
[MiaoYz][23:38:58.531][INFO] recv from: [Group: 枫迹の交流群①(303104111), Member: 枫音酱(1932289274)] {image:C0AA009A9A38DBF08F0272521E9D43F2}
[MiaoYz][23:38:58.538][INFO] recv from: [Group: 枫迹の交流群①(303104111), Member: 枫音酱(1932289274)] {image:C0AA009A9A38DBF08F0272521E9D43F2}
[MiaoYz][23:38:58.544][INFO] succeed to send: [Group(303104111)] [图片]
[MiaoYz][23:38:58.544][MARK] [椰奶状态][state] #状态 处理完成 3631ms
[MiaoYz][23:38:58.583][ERRO] TypeError: Cannot read properties of undefined (reading 'group_id')
    at PluginsLoader.checkDisable (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/lib/plugins/loader.js:709:39)
    at file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:37:23
    at Array.forEach (<anonymous>)
    at PluginsLoader.deal (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:33:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/cmd.js:85:13)
[MiaoYz][23:38:58.609][ERRO] TypeError: Cannot read properties of undefined (reading 'group_id')
    at PluginsLoader.checkDisable (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/lib/plugins/loader.js:709:39)
    at file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:37:23
    at Array.forEach (<anonymous>)
    at PluginsLoader.deal (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:33:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/cmd.js:85:13)
[MiaoYz][23:38:58.656][ERRO] TypeError: Cannot read properties of undefined (reading 'group_id')
    at PluginsLoader.checkDisable (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/lib/plugins/loader.js:709:39)
    at file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:37:23
    at Array.forEach (<anonymous>)
    at PluginsLoader.deal (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:33:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/cmd.js:85:13)
[MiaoYz][23:39:37.095][INFO] recv from: [Group: 孤独摇滚(聊天群)(692032814), Member: 包贝(包老师)(1923285335)] {image:67A240BA375AA259C08AAB01263ED026}
[MiaoYz][23:39:37.116][INFO] [咸鱼_统计][adduser][孤独摇滚(聊天群)(包贝(包老师))] 
[MiaoYz][23:39:40.887][INFO] recv from: [Group: 孤独摇滚(聊天群)(692032814), Member: 包贝(包老师)(1923285335)] Ok，粉丝发要求
[MiaoYz][23:39:40.904][INFO] [咸鱼_统计][adduser][孤独摇滚(聊天群)(包贝(包老师))] Ok，粉丝发要求
[MiaoYz][23:40:01.880][INFO] recv from: [Group: 孤独摇滚(聊天群)(692032814), Member: 包贝(包老师)(1923285335)] 不多说
[MiaoYz][23:40:01.899][INFO] [咸鱼_统计][adduser][孤独摇滚(聊天群)(包贝(包老师))] 不多说
[MiaoYz][23:40:04.869][INFO] recv from: [Group: 孤独摇滚(聊天群)(692032814), Member: 包贝(包老师)(1923285335)] 上电脑！
[MiaoYz][23:40:04.887][INFO] [咸鱼_统计][adduser][孤独摇滚(聊天群)(包贝(包老师))] 上电脑！
[MiaoYz][23:40:12.131][INFO] recv from: [Group: Black Evil-黑恶发情季(1094060150), Member: 狗某| Doginthis (3376665045)] {image:9ED8126C701301DFCF25603141F9F723}
[MiaoYz][23:40:12.280][ERRO] TypeError: Cannot read properties of undefined (reading 'group_id')
    at PluginsLoader.checkDisable (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/lib/plugins/loader.js:709:39)
    at file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:37:23
    at Array.forEach (<anonymous>)
    at PluginsLoader.deal (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/loader.js:33:23)
    at async Client.<anonymous> (file:///C:/Users/Dnyo/Desktop/miao-fix/Miao-Yunzai/plugins/icqq-plugin/model/cmd.js:85:13)

**Comment by Dnyo666** [comment]
根据你提供的错误信息，看起来你遇到了 JavaScript 代码中的 TypeError。具体来说，它表示无法读取未定义的属性 'group_id'。这个错误在你的代码库中的多个地方都出现了，很可能与 PluginsLoader 类和 icqq-plugin 有关。

以下是错误消息的分析：

错误发生在 PluginsLoader 类的 loader.js 文件的第 709 行。
它似乎发生在 icqq-plugin 的 loader.js 文件的第 37 行。
错误发生在尝试读取未定义的 'group_id' 属性时。
在 PluginsLoader 中的 checkDisable 函数是触发此错误的地方。
这个错误似乎与应用程序中的群组处理有关。
要解决这个问题，你需要调试代码，找出为什么在这些情况下 'group_id' 是未定义的。检查是否在访问之前正确初始化或获取了 group_id。确保在尝试访问属性之前，所有必要的数据都是可用的。此外，验证所有必要的依赖项是否被正确加载，并查看是否存在可能导致 'group_id' 未定义的任何异步操作。

你提供的错误日志中的最后一行似乎与 TypeError 无关，并指示了与签名 API 异常相关的不同问题。如果这会在你的应用程序中造成问题，你可能需要单独进行调查。

**Comment by 8852690** [comment]
icqq-plugin? 这个插件已经半年没更新了, 可能会存在一定的适配问题, 需要慢慢检查才知道, 你是需要icqq多开吗?

**Comment by Dnyo666** [comment]
是的，是用https://github.com/Loli-Lain/icqq-plugin的插件，貌似跑路没更新了

**Comment by 8852690** [comment]
> 是的，是用[https://github.com/Loli-Lain/icqq-plugin的插件，貌似跑路没更新了](https://github.com/Loli-Lain/icqq-plugin%E7%9A%84%E6%8F%92%E4%BB%B6%EF%BC%8C%E8%B2%8C%E4%BC%BC%E8%B7%91%E8%B7%AF%E6%B2%A1%E6%9B%B4%E6%96%B0%E4%BA%86)

如果有必要使用多ICQQ的话, 或许你可以考虑使用Trss-Yunzai, 它本身就支持多ICQQ登录.

**Comment by Dnyo666** [comment]
但是，我不能确保所有插件的兼容性，所以按照目前的需求，其实可以尝试做个迁移，备份一个，麻烦你了

**Comment by devil233-ui** [comment]
> 但是，我不能确保所有插件的兼容性，所以按照目前的需求，其实可以尝试做个迁移，备份一个，麻烦你了

请问找到到方案了吗
