### ISSUE TITLE
图片生成失败

### ISSUE THREAD

**Issue by Youc2628** [yoimiya-kokomi/Miao-Yunzai#465]
报错如下
`[MiaoYz][10:52:28.826][INFO] recv from: [Private: 2628647570(friend)] #菜单
[MiaoYz][10:52:29.253][INFO] [喵喵:喵喵帮助][help][私聊][夏目贵志(2628647570)] #菜单
[MiaoYz][10:52:29.259][INFO] puppeteer Chromium 启动中...
[MiaoYz][10:52:29.673][INFO] puppeteer Chromium 启动成功 ws://127.0.0.1:40021/devtools/browser/b4cbd5ed-e878-4010-a7bb-8afb4eaf8568
[MiaoYz][10:52:29.767][ERRO] [图片生成][miao-plugin/help/index] 图片生成失败 Error: net::ERR_FILE_NOT_FOUND at file:///home/youc/Miao-Yunzai/temp/html/miao-plugin/help/index/index.html
    at navigate (file:///home/youc/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@22.8.2/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:172:27)
    at async Deferred.race (file:///home/youc/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@22.8.2/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:33:20)
    at async CdpFrame.goto (file:///home/youc/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@22.8.2/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:138:25)
    at async CdpPage.goto (file:///home/youc/Miao-Yunzai/node_modules/.pnpm/puppeteer-core@22.8.2/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:558:20)
    at async Puppeteer.screenshot [as render] (file:///home/youc/Miao-Yunzai/renderers/puppeteer/lib/puppeteer.js:187:7)
    at async renderer.screenshot (file:///home/youc/Miao-Yunzai/lib/puppeteer/puppeteer.js:10:15)
    at async Runtime.render (file:///home/youc/Miao-Yunzai/lib/plugins/runtime.js:236:18)
    at async cls.render (file:///home/youc/Miao-Yunzai/plugins/miao-plugin/apps/help/Help.js:61:12)
    at async cls.<computed> [as help] (file:///home/youc/Miao-Yunzai/plugins/miao-plugin/components/App.js:96:18)
    at async PluginsLoader.deal (file:///home/youc/Miao-Yunzai/lib/plugins/loader.js:275:41)
[MiaoYz][10:52:29.770][INFO] puppeteer Chromium 强制关闭重启...
[MiaoYz][10:52:29.771][INFO] puppeteer Chromium 启动中...
[MiaoYz][10:52:29.772][MARK] [喵喵:喵喵帮助][help] #菜单 处理完成 519ms
[MiaoYz][10:52:30.200][INFO] puppeteer Chromium 启动成功 ws://127.0.0.1:37147/devtools/browser/920eca97-6faf-4579-ad23-bb760c0dcde2`
![0f29effc3abea883782586f43c62d58b](https://github.com/user-attachments/assets/8398ae18-41ec-4646-a429-719cfa94403d)
puppeteer换了几个版本也不行，重新安装几遍还是一样

**Comment by lin-junliang** [comment]
pnpm uninstall puppeteer 
pnpm add puppeteer@13.7.0 -w
node ./node_modules/puppeteer/install.js

**Comment by S-t-e-v-e-e** [comment]
> pnpm uninstall puppeteer pnpm add puppeteer@13.7.0 -w node ./node_modules/puppeteer/install.js

问一下报错
```
TypeError: puppeteer.launch is not a function
    at Puppeteer.browserInit (file:///root/TRSS_AllBot/Miao-Yunzai/renderers/puppeteer/lib/puppeteer.js:85:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Puppeteer.screenshot (file:///root/TRSS_AllBot/Miao-Yunzai/renderers/puppeteer/lib/puppeteer.js:162:10)
    at async newPuppeteer.render (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/phi-plugin/model/puppeteer.js:114:22)
    at async picmodle.render (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/phi-plugin/model/picmodle.js:181:27)
    at async picmodle.common (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/phi-plugin/model/picmodle.js:158:16)
    at async picmodle.b19 (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/phi-plugin/model/picmodle.js:42:16)
    at async phib19.b19 (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/phi-plugin/apps/b19.js:209:30)
    at async PluginsLoader.deal (file:///root/TRSS_AllBot/Miao-Yunzai/lib/plugins/loader.js:275:41)
```
是什么问题呢

**Comment by miaomiao2970** [comment]
> pnpm uninstall puppeteer pnpm add puppeteer@13.7.0 -w node ./node_modules/puppeteer/install.js

换这个低版本：{}
[MiaoYz][03:32:51.776][ERRO] Error: Failed to launch the browser process!
/Miao-Yunzai/node_modules/.pnpm/puppeteer@13.7.0_encoding@0.1.13/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/Miao-Yunzai/node_modules/.pnpm/puppeteer@13.7.0_encoding@0.1.13/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/Miao-Yunzai/node_modules/.pnpm/puppeteer@13.7.0_encoding@0.1.13/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:529:35)
    at Interface.close (node:internal/readline/interface:534:10)
    at Socket.onend (node:internal/readline/interface:260:10)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined
[MiaoYz][03:32:51.777][ERRO] puppeteer Chromium 启动失败
