### ISSUE TITLE
重启报错，有dalao能不能帮忙看下是哪的问题

### ISSUE THREAD

**Issue by akmioto** [yoimiya-kokomi/Miao-Yunzai#62]
Error: Command failed: pnpm start
[PM2][ERROR] Process 0 not found
Process 0 not found
C:\111\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\API.js:1717
        acted.push(proc.pm2_env ? proc.pm2_env.pm_id : proc.pm_id)
                        ^

TypeError: Cannot read properties of undefined (reading 'pm2_env')
    at C:\111\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\API.js:1717:25
    at Array.forEach (<anonymous>)
    at API.speedList (C:\111\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\API.js:1716:18)
    at C:\111\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\binaries\CLI.js:301:15
    at wrapper (C:\111\Miao-Yunzai\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\once.js:12:16)
    at replenish (C:\111\Miao-Yunzai\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\eachOfLimit.js:76:25)
    at iterateeCallback (C:\111\Miao-Yunzai\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\eachOfLimit.js:65:17)
    at C:\111\Miao-Yunzai\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\onlyOnce.js:12:16
    at C:\111\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\binaries\CLI.js:292:11
    at C:\111\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\API.js:330:21

Node.js v19.9.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

**Comment by yelinlan** [comment]
https://stackoverflow.com/questions/69099139/cannot-read-property-pm2-env-of-undefined

1.npm install pm2@latest -g #更新到最新
2.pm2 update #
3.ps -ef | grep pm2 kill -9 <PID_OF_PM2> #关闭pm2
4.应该就好了
