### ISSUE TITLE
TypeError: rendererFn is not a function

### ISSUE THREAD

**Issue by yiming-zh** [yoimiya-kokomi/Miao-Yunzai#68]
更新后使用node app都会报这个错误
`[MiaoYz][11:23:31.760][ERRO] TypeError: rendererFn is not a function
    at registerRendererBackends (file:///home/user/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
    at async file:///home/zym/Miao-Yunzai/lib/renderer/Renderer.js:32:1
[MiaoYz][11:23:31.766][MARK] 监听事件错误：message.js
[MiaoYz][11:23:31.766][ERRO] TypeError: rendererFn is not a function
    at registerRendererBackends (file:///home/user/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
    at async file:///home/zym/Miao-Yunzai/lib/renderer/Renderer.js:32:1
[MiaoYz][11:23:31.768][MARK] 监听事件错误：notice.js
[MiaoYz][11:23:31.769][ERRO] TypeError: rendererFn is not a function
    at registerRendererBackends (file:///home/user/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
    at async file:///home/zym/Miao-Yunzai/lib/renderer/Renderer.js:32:1
[MiaoYz][11:23:31.773][MARK] 监听事件错误：offline.js
[MiaoYz][11:23:31.776][ERRO] TypeError: rendererFn is not a function
    at registerRendererBackends (file:///home/user/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
    at async file:///home/zym/Miao-Yunzai/lib/renderer/Renderer.js:32:1
[MiaoYz][11:23:31.778][MARK] 监听事件错误：online.js
[MiaoYz][11:23:31.778][ERRO] TypeError: rendererFn is not a function
    at registerRendererBackends (file:///home/user/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
    at async file:///home/zym/Miao-Yunzai/lib/renderer/Renderer.js:32:1
[MiaoYz][11:23:31.782][MARK] 监听事件错误：request.js
[MiaoYz][11:23:31.785][ERRO] TypeError: rendererFn is not a function
    at registerRendererBackends (file:///home/user/Miao-Yunzai/lib/renderer/Renderer.js:23:20)
    at async file:///home/zym/Miao-Yunzai/lib/renderer/Renderer.js:32:1`

跟踪后发现相关代码如下
`let rendererBackends = {}

async function registerRendererBackends () {
  const subFolders = fs.readdirSync(`${process.cwd()}/renderers`, { withFileTypes: true }).filter((dirent) => dirent.isDirectory())
  for (let subFolder of subFolders) {
    let name = subFolder.name
    const rendererFn = await Data.importDefault(`/renderers/${name}/index.js`)
    let configFile = `./renderers/${name}/config.yaml`
    let rendererCfg = {}
    if (fs.existsSync(configFile)) {
      try {
        rendererCfg = yaml.parse(fs.readFileSync(configFile, 'utf8'))
      } catch (e) {
        rendererCfg = {}
      }
    }
    let renderer = rendererFn(rendererCfg)
    if (!renderer.id || !renderer.type || !renderer.render || !lodash.isFunction(renderer.render)) {
      logger.warn('渲染后端 ' + (renderer.id || subFolder.name) + ' 不可用')
    }
    rendererBackends[renderer.id] = renderer
    logger.mark('[渲染后端加载]: 导入 ' + renderer.id)
  }`
怀疑可能和renderers修改有关

**Comment by xiaofeiTM233** [comment]
把之前的换进去试试？

**Comment by yiming-zh** [comment]
反馈：
暂时解决该问题
git checkout 5126c6c7f542806020b9386bb0edbf62b00aaa33
切换到4.17的版本后node app恢复正常
