### ISSUE TITLE
#重启失败，还是老毛病

### ISSUE THREAD

**Issue by lzm654** [yoimiya-kokomi/Miao-Yunzai#82]
操作失败！
Error: Command failed: pnpm start
[PM2][ERROR] Process 0 not found
Process 0 not found
C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\API.js:1717
        acted.push(proc.pm2_env ? proc.pm2_env.pm_id : proc.pm_id)
                        ^

TypeError: Cannot read properties of undefined (reading 'pm2_env')
    at C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\API.js:1717:25
    at Array.forEach (<anonymous>)
    at API.speedList (C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\API.js:1716:18)
    at C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\binaries\CLI.js:301:15
    at wrapper (C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\once.js:12:16)
    at replenish (C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\eachOfLimit.js:76:25)
    at iterateeCallback (C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\eachOfLimit.js:65:17)
    at C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\onlyOnce.js:12:16
    at C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\binaries\CLI.js:292:11
    at C:\yunzaiv3\Miao-Yunzai\node_modules\.pnpm\pm2@5.3.0\node_modules\pm2\lib\API.js:330:21

    at ChildProcess.exithandler (node:child_process:400:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

疑似是pnpm版本问题

**Comment by mihneamanolache** [comment]
Facing a similar issue. What version of NodeJS are you using and have you tried with other versions? Thanks!

**Comment by lzm654** [comment]
> https://stackoverflow.com/questions/69099139/cannot-read-property-pm2-env-of-undefined
> 
> 1.npm install pm2@latest -g #更新到最新 2.pm2 update # 3.ps -ef | grep pm2 kill -9 <PID_OF_PM2> #关闭pm2 4.应该就好了

经尝试未解决问题，可能还是跟node版本有关系吧，#关机 js也不能执行，表面上关了但是如关。

**Comment by yelinlan** [comment]
> > > > https://stackoverflow.com/questions/69099139/cannot-read-property-pm2-env-of-undefined
> > > > 1.npm install pm2@latest -g #更新到最新 2.pm2 update # 3.ps -ef | grep pm2 kill -9 <PID_OF_PM2> #关闭pm2 4.应该就好了
> > > 
> > > 
> > > 经尝试未解决问题，可能还是跟node版本有关系吧，#关机 js也不能执行，表面上关了但是如关。
> > 
> > 
> > 我是刚遇到这个问题，我把依赖全删了，又安装，就出现了，找了半天。网上才找到解决办法。
> 
> 你的node版本是多少

![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/38036830/d889d89f-581c-4518-a5aa-3675e566d37c)

**Comment by lzm654** [comment]
> > > > https://stackoverflow.com/questions/69099139/cannot-read-property-pm2-env-of-undefined
> > > > 1.npm install pm2@latest -g #更新到最新 2.pm2 update # 3.ps -ef | grep pm2 kill -9 <PID_OF_PM2> #关闭pm2 4.应该就好了
> > > 
> > > 
> > > 经尝试未解决问题，可能还是跟node版本有关系吧，#关机 js也不能执行，表面上关了但是如关。
> > 
> > 
> > 我是刚遇到这个问题，我把依赖全删了，又安装，就出现了，找了半天。网上才找到解决办法。
> 
> 你的node版本是多少



> > > https://stackoverflow.com/questions/69099139/cannot-read-property-pm2-env-of-undefined
> > > 1.npm install pm2@latest -g #更新到最新 2.pm2 update # 3.ps -ef | grep pm2 kill -9 <PID_OF_PM2> #关闭pm2 4.应该就好了
> > 
> > 
> > 经尝试未解决问题，可能还是跟node版本有关系吧，#关机 js也不能执行，表面上关了但是如关。
> 
> 我是刚遇到这个问题，我把依赖全删了，又安装，就出现了，找了半天。网上才找到解决办法。

我从node16.18升级到18.16并不能解决问题，且问题出现在yunzai升级至miao-yunzai之后。可能也有某种联系。
