### ISSUE TITLE
定时任务报错：米游社公告推送任务

### ISSUE THREAD

**Issue by akmioto** [yoimiya-kokomi/Miao-Yunzai#85]
[12:55:00.170][ERRO] 定时任务报错：米游社公告推送任务
[12:55:00.171][ERRO] TypeError: Cannot read properties of undefined (reading 'gl')
    at MysNews.sendNews (file:///C:/111/Miao-Yunzai/plugins/genshin/model/mysNews.js:326:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MysNews.mysNewsTask (file:///C:/111/Miao-Yunzai/plugins/genshin/model/mysNews.js:307:11)
    at async mysNews.mysNewsTask (file:///C:/111/Miao-Yunzai/plugins/genshin/apps/mysNews.js:71:5)
    at async Job.job (file:///C:/111/Miao-Yunzai/lib/plugins/loader.js:604:48)
[13:00:00.598][ERRO] 定时任务报错：米游社公告推送任务
[13:00:00.599][ERRO] TypeError: Cannot read properties of undefined (reading 'gl')
    at MysNews.sendNews (file:///C:/111/Miao-Yunzai/plugins/genshin/model/mysNews.js:326:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MysNews.mysNewsTask (file:///C:/111/Miao-Yunzai/plugins/genshin/model/mysNews.js:307:11)
    at async mysNews.mysNewsTask (file:///C:/111/Miao-Yunzai/plugins/genshin/apps/mysNews.js:71:5)
    at async Job.job (file:///C:/111/Miao-Yunzai/lib/plugins/loader.js:604:48)

今天刚出现的，上次公告推送正常

**Comment by meng-fucius** [comment]
+1，我也出现了
<img width="807" alt="image" src="https://user-images.githubusercontent.com/71968682/234189388-2c7aa1d8-9f94-47c6-9895-8e9581797b8f.png">
