### ISSUE TITLE
node app启动程序直接报错

### ISSUE THREAD

**Issue by 443127105** [yoimiya-kokomi/Miao-Yunzai#89]
/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/composer.js:69
                this.errors.push(new errors.YAMLParseError(pos, code, message));
                                 ^

YAMLParseError: Missing closing 'quote at line 6, column 12:

platform: 6
           ^

    at Composer.onError (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/composer.js:69:34)
    at _onError (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/resolve-flow-scalar.js:10:42)
    at singleQuotedValue (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/resolve-flow-scalar.js:73:9)
    at Object.resolveFlowScalar (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/resolve-flow-scalar.js:18:21)
    at Object.composeScalar (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/compose-scalar.js:11:29)
    at composeNode (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/compose-node.js:24:34)
    at Object.resolveBlockMap (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/resolve-block-map.js:80:19)
    at Object.composeCollection (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/compose-collection.js:13:36)
    at Object.composeNode (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/compose-node.js:31:38)
    at Object.composeDoc (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/compose-doc.js:32:23) {
  code: 'MISSING_CHAR',
  pos: [ 126, 127 ],
  linePos: [ { line: 6, col: 12 }, { line: 6, col: 13 } ]
}

Node.js v18.15.0

我纯小白，看不懂这个报错是什么意思。我试着打开了这个composer.js，并没有发现什么'缺失的问题。

**Comment by xfdown** [comment]
你需要先更新icqq到0.3.x

**Comment by 443127105** [comment]
> 你需要先更新icqq到0.3.x

请问如何更新这个？Yunzai现在不自带icqq了吗？

**Comment by xfdown** [comment]
> > 你需要先更新icqq到0.3.x
> 
> 请问如何更新这个？云扎伊现在不自带icqq了吗？

先把miao-yunzai更新到最新，然后执行pnpm update应该就可以了。

**Comment by xfdown** [comment]
> > 
> 
> 执行git pull root@localhost:~/Miao-Yunzai# git pull Already up to date.
> 
> 执行pnpm update root@localhost:~/Miao-Yunzai# pnpm update  ERR_PNPM_INCLUDED_DEPS_CONFLICT  modules directory (at "/root/Miao-Yunzai") was installed with optionalDependencies, dependencies. Current install wants optionalDependencies, dependencies, devDependencies.

呃，你按你之前装依赖的方法执行一下吧。。

**Comment by xfdown** [comment]
> > 
> 
> 执行git pull root@localhost:~/Miao-Yunzai# git pull Already up to date.
> 
> 执行pnpm update root@localhost:~/Miao-Yunzai# pnpm update  ERR_PNPM_INCLUDED_DEPS_CONFLICT  modules directory (at "/root/Miao-Yunzai") was installed with optionalDependencies, dependencies. Current install wants optionalDependencies, dependencies, devDependencies.

或者试试pnpm add icqq@0.3.1 -w

**Comment by 443127105** [comment]
> > 执行git pull root@localhost:~/Miao-Yunzai# git pull Already up to date.
> > 执行pnpm update root@localhost:~/Miao-Yunzai# pnpm update  ERR_PNPM_INCLUDED_DEPS_CONFLICT  modules directory (at "/root/Miao-Yunzai") was installed with optionalDependencies, dependencies. Current install wants optionalDependencies, dependencies, devDependencies.
> 
> 或者试试pnpm add icqq@0.3.1 -w

同样的报错。
之前安装依赖的时候也没装过icqq这个包啊，我是找了一个chrome依赖库的命令装好就正常运行了。昨天开始qq掉了提示版本过低，我试了几次node app login换设备型号忽然就这样了。

**Comment by xfdown** [comment]
话说，我搞错了，这不是icqq的问题。。

**Comment by xfdown** [comment]
你把qq.yaml删掉重新登陆看看。

**Comment by 443127105** [comment]
> 你把qq.yaml删掉重新登陆看看。

这个文件在哪里？

**Comment by xfdown** [comment]
config/config/qq.yaml

**Comment by 443127105** [comment]
> config/config/qq.yaml

启动了！不过我想知道这是什么问题，为什么会导致这样？
此外它现在仍然提示QQ版本过低怎么解决……还是无法正常使用啊😂
